code style
wolkykim/qlibc pull request #103
Opened 2023-07-10 10:49 UTC by Hojun-Cho

I found other things that needed fixing, so I recreated the PR.
modified: 'if('  =>  'if ('. Is okay?

2023-07-10 19:52 UTC, wolkykim commented on src/internal/qinternal.h
>          for(_strsize = 1024; ; _strsize *= 2) {                         \
do we want to style this the same way?

2023-07-10 19:54 UTC, wolkykim commented on src/internal/qinternal.h
> +            if (s == NULL) {                                             \
we want the tailing `\` lineup with other lines

2023-07-10 19:57 UTC, wolkykim commented
thanks for the PR. I left a few comments. Have you checked other files? Are those the only files needing style adjustment?

2023-07-10 19:58 UTC, wolkykim commented
sorry clicked the wrong button. reopened.

2023-07-11 00:19 UTC, Hojun-Cho commented
> thanks for the PR. I left a few comments. Have you checked other files? Are those the only files needing style adjustment?

Maybe we should style the comments too? If not, I think we're done.

2023-07-12 05:14 UTC, wolkykim requested changes

2023-07-12 05:14 UTC, wolkykim commented on src/internal/qinternal.h
> +        for (_strsize = 1024; ; _strsize *= 2) {                         \
the tailing `\` are off lining up with others.

2023-07-12 05:14 UTC, wolkykim commented on src/internal/qinternal.h
> +            if (_n >= 0 && _n < _strsize) break;                         \
the tailing `\` are off lining up with others here too. This is happening for many of the updates. Please check them again. Maybe easier to see it on the diff UI https://github.com/wolkykim/qlibc/pull/103/files

2023-07-12 05:45 UTC, Hojun-Cho commented
Fixed. Thanks for letting me know. Are the changes correct?

2023-07-12 05:47 UTC, Hojun-Cho commented
Fixed. Thanks for letting me know. Are the changes correct?

2023-07-12 06:30 UTC, wolkykim reviewed
What's your plan for other files? Are you going to work on applying this convention to all the other code and header files? Or partially only to those files included in this PR?

2023-07-12 06:30 UTC, wolkykim commented on src/internal/qinternal.h
> +        }                                                                    \
You only need to update L79 and L84.

2023-07-12 06:57 UTC, Hojun-Cho commented
I created the PR because I enjoy looking at qlibc code. I don't plan to apply this rule to any other files (though I will if you need to).. am I messing with qlibc code?

2023-07-12 07:31 UTC, wolkykim commented
That's nice. And no, you're not messing with the code but making it better. I appreciate your work. Yeah, making everything consistent would be nice but it's a large work.

2023-07-12 07:36 UTC, wolkykim approved these changes

2023-07-12 07:37 UTC, merged

2023-07-12 08:33 UTC, Hojun-Cho commented
Thank you for creating such a great library ^%^.